name: Pull request pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy-dev-web-app:

runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: ghcr.io
username: ${{ github.actor }}
password: ${{ secrets.GITHUB_TOKEN }}
- name: Build the hello-docker Docker image
run: |
       docker build . --tag ghcr.io/faridkhouda/hello-docker-gcr-demo:latest
       docker run ghcr.io/faridkhouda/hello-docker-gcr-demo:latest
       docker push ghcr.io/faridkhouda/hello-docker-gcr-demo:latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install depedency
        run: npm install

  