name: Pull request pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy-dev-web-app:
    # container:
    #   image: 
    #   volumes:
    #     - 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install depedency
        run: npm install

  
