name: Pull request pipeline

on: pull_request

jobs:
  testing:
    # container:
    #   image:
    #   volumes:
    #     -
    
    runs-on: ubuntu-latest
    steps:
      - name: Collect Workflow Telemetry
        uses: runforesight/foresight-workflow-kit-action@v1
        if: ${{ always() }}
        with:
          api_key: 2bac4536-69d9-4240-b7df-3abc6ac08141
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install depedency
        run: npm install
      - name: Building web app
        run: npm run build
        
      - name: Analyze Test and/or Coverage Results
        uses: runforesight/foresight-test-kit-action@v1
        if: ${{ always() }}
        with:
          api_key: 2bac4536-69d9-4240-b7df-3abc6ac08141
          test_format: Jasmine
          test_framework: Jasmine

